title: Isin Altinkaya
url: "https://isinaltinkaya.github.io"
baseurl: "."

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
#footer_url: "https://github.com/isinaltinkaya"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "cv"
 - name: "Research"
   link: "research"
 - name: "Blog"
   link: "blog"
 - name: "Contact"
   link: "contact"
# - name: "Misc"
#   link: "/misc/"

remote_theme: ankitsultana/researcher@gem
