title: Işın Altınkaya, BSc c.
url: "https://isinaltinkaya.github.io"
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: no
#footer_url: "https://github.com/isinaltinkaya"
#footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "CV"
   link: "IsinAltinkaya_CV.pdf"
 - name: "Research"
   link: "research"
 - name: "Contact"
   link: "contact"

remote_theme: ankitsultana/researcher@gem
